[project]
name = "msensor-plot-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "grpcio-tools==1.71.0",
    "pyqt5==5.15.11",
    "pyqtgraph==0.13.7",
]
